---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: change, settings, mirrored, pair, volume, adjust, percentage, point, system, manager, alert, notification, reserved, capacity, full 
summary: ミラーペアボリュームの設定を変更して、ミラーペアボリュームのリザーブ容量が残り少なくなったときにSystem Managerからアラート通知を送信する割合を調整できます。 
---
= ミラーペアボリュームのリザーブ容量の設定を変更する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ミラーペアボリュームの設定を変更して、ミラーペアボリュームのリザーブ容量が残り少なくなったときにSystem Managerからアラート通知を送信する割合を調整できます。

.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. 予約容量*タブを選択します。
. 編集するミラーペアボリュームを選択し、*表示/設定の編集*をクリックします。
+
ミラーペアボリュームのリザーブ容量設定*ダイアログボックスが表示されます。

. ミラーペアボリュームのリザーブ容量設定を適宜変更します。
+
.フィールドの詳細
[%collapsible]
====
[cols="1a,3a"]
|===
| 設定 | 説明 


 a| 
アラートの送信しきい値
 a| 
このスピンボックスを使用して、ミラーペアのリザーブ容量が残り少なくなったときにSystem Managerからアラート通知を送信する割合を調整します。

ミラーペアのリザーブ容量が指定したしきい値を超えるとSystem Managerからアラートが送信されるため、前もってリザーブ容量を増やすことができます。


NOTE: 1つのミラーペアのアラート設定を変更すると、同じミラー整合性グループに属するすべてのミラーペアのアラート設定が変更されます。



 a| 
リザーブ容量がフルになったときの処理です
 a| 
次のいずれかのポリシーを選択できます。

** *最も古いSnapshotイメージをパージする*–System Managerによって整合性グループの最も古いSnapshotイメージが自動的にパージされ、メンバーのリザーブ容量が解放されてグループ内で再利用されます。
** *ベースボリュームへの書き込みを拒否する*–リザーブ容量の割合が定義された上限に達すると、System Managerはリザーブ容量へのアクセスをトリガーしたベースボリュームに対するI/O書き込み要求をすべて拒否します。


|===
====
. [保存（Save）]をクリックして、変更を適用します。


.結果
System Managerはメンバーボリュームのリザーブ容量設定だけでなく、整合性グループ内のすべてのメンバーボリュームのリザーブ容量設定を変更します。
