---
permalink: sm-storage/create-pool-automatically.html 
sidebar: sidebar 
keywords: pool, creation, initiated, automatically, system, manager, detect, unassigned, drives, storage, array, configure, add, existing 
summary: プールの作成は、System Managerがストレージアレイ内に未割り当てのドライブを検出すると自動的に開始されます。プールの自動作成を使用すると、ストレージアレイ内のすべての未割り当てドライブを1つのプールに簡単に設定したり、既存のプールにドライブを追加したりできます。 
---
= プールを自動的に作成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プールの作成は、System Managerがストレージアレイ内に未割り当てのドライブを検出すると自動的に開始されます。プールの自動作成を使用すると、ストレージアレイ内のすべての未割り当てドライブを1つのプールに簡単に設定したり、既存のプールにドライブを追加したりできます。

次のいずれかの条件に該当する場合は、* Pool Auto-Configuration *ダイアログボックスを起動できます。

* ドライブタイプが類似する既存のプールに追加できる未割り当てドライブが1本以上検出された場合。
* 新しいプールの作成に使用できる未割り当てドライブが11本以上検出された場合（ドライブタイプが異なるために既存のプールに追加できない場合）。


次の点に注意してください。

* ストレージアレイにドライブを追加すると、System Managerではドライブが自動的に検出され、ドライブタイプと現在の構成に基づいて、1つまたは複数のプールを作成するように求められます。
* プールが以前に定義されている場合、互換性があるドライブを既存のプールに追加するかどうかを確認するメッセージがSystem Managerで自動的に表示されます。新しいドライブを既存のプールに追加すると、System Managerによって、追加した新しいドライブを含む新しい容量にデータが自動的に再配分されます。
* EF600ストレージアレイを構成する場合は、各コントローラが最初の12個のスロットと残りの12個のスロットに同じ数のドライブにアクセスできることを確認します。この構成により、コントローラは両方のドライブ側PCIeバスをより効果的に使用できます。現在のところ、System Managerでは、ボリュームグループの作成時に詳細設定機能でドライブを選択できます。プールを作成する場合は、ストレージアレイのすべてのドライブを使用することを推奨します。


以下のいずれかの方法を使用して、* Pool Auto-Configuration *ダイアログボックスを起動できます。

* 未割り当て容量が検出されると、通知領域のホームページにプールの自動構成に関する推奨事項が表示されます。View Pool Auto-Configuration *（プールの自動構成の表示）をクリックして、ダイアログボックスを起動します。
* プールとボリュームグループページから*プールの自動構成*ダイアログボックスを起動することもできます。これには次のタスクを実行します。


.手順
. 選択メニュー：Storage（Pool & Volume Groups）
. メニューを選択します。More [Launch pool auto-configuration]。
+
新しいプール、ドライブが追加されている既存のプール、またはその両方が表示されます。新しいプールには、連番を付した名前がデフォルトで付けられます。

+
System Managerでは次の処理が行われます。

+
** ドライブタイプ（HDDまたはSSD）が同じで容量が同等の十分な数のドライブがある場合は、単一のプールを作成する。
** 未割り当て容量が異なるドライブタイプで構成されている場合は、複数のプールを作成する。
** ストレージアレイにすでにプールが定義されている場合、追加した新しいドライブのドライブタイプが既存のプールと同じであれば、そのプールにドライブが追加されます。
** タイプの異なる複数のドライブを追加した場合は、ドライブタイプが同じドライブを既存のプールに追加し、別のドライブタイプのドライブを使用して別のプールを作成する。


. 新しいプールの名前を変更するには、* Edit *アイコン（鉛筆）をクリックします。
. プールのその他の特性を表示するには、カーソルを合わせるか、* Details *アイコン（ページ）をタッチします。
+
ドライブタイプ、セキュリティ機能、Data Assurance（DA）機能、シェルフ損失の保護、ドロワー損失の保護に関する情報が表示されます。

. [* 同意する * ] をクリックします。

