---
permalink: sm-storage/decide-to-use-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: create, volumes, using, either, pool, group, selection, depend, primarily, key, storage, requirements, expect, workload, performance, data, protection 
summary: ボリュームはプールまたはボリュームグループを使用して作成できます。どちらが適しているかは、主に、予想されるI/Oワークロードなどの主要なストレージ要件、パフォーマンス要件、データ保護要件によって決まります。 
---
= プールとボリュームグループのどちらを使用するかを決定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームはプールまたはボリュームグループを使用して作成できます。どちらが適しているかは、主に、予想されるI/Oワークロードなどの主要なストレージ要件、パフォーマンス要件、データ保護要件によって決まります。



== プールまたはボリュームグループを選択する理由

*プールを選択*

* ドライブのリビルド時間を短縮し、ストレージ管理を簡易化する必要がある場合、シンボリュームが必要な場合、大量のランダムワークロードが発生している場合。
* 各ボリュームのデータをプールを構成する一連のドライブにランダムに分散する場合。
+
プールまたはプール内のボリュームのRAIDレベルは設定または変更できません。プールではRAIDレベル6を使用します。



*ボリュームグループを選択*

* システムの帯域幅を最大限に使用する必要がある場合、ストレージの設定を調整する機能、大量のシーケンシャルワークロードを利用する場合。
* データをRAIDレベルに基づいてドライブに分散する場合。ボリュームグループは作成時にRAIDレベルを指定できます。
* 各ボリュームのデータをボリュームグループを構成する一連のドライブにシーケンシャルに書き込む場合。


[NOTE]
====
プールとボリュームグループは共存可能なため、ストレージアレイにプールとボリュームグループの両方を含めることができます。

====


== プールとボリュームグループの機能の違い

次の表に、ボリュームグループとプールの機能の比較を示します。

[cols="3*"]
|===
| 使用 | プール | ボリュームグループ 


 a| 
ランダムワークロード
 a| 
より良い
 a| 
良好です



 a| 
シーケンシャルワークロード
 a| 
良好です
 a| 
より良い



 a| 
ドライブのリビルド時間
 a| 
高速化
 a| 
遅い



 a| 
パフォーマンス（最適モード）
 a| 
良い：小さなブロックのランダムワークロードに最適
 a| 
良い：大きなブロックのシーケンシャルワークロードに最適



 a| 
パフォーマンス（ドライブリビルドモード）
 a| 
より良い：通常はRAID 6よりも良い
 a| 
Degraded：パフォーマンスが最大40%低下します



 a| 
複数のドライブ障害が発生した場合
 a| 
データ保護機能に優れる：リビルドを優先し、高速に処理
 a| 
データ保護機能が劣る：リビルドが遅く、データ損失のリスクが大きい



 a| 
ドライブの追加
 a| 
速い：オンザフライでプールに追加できます
 a| 
遅い：Dynamic Capacity Expansion処理が必要です



 a| 
シンボリュームがサポートされます
 a| 
はい。
 a| 
いいえ



 a| 
ソリッドステートディスク（SSD）のサポート
 a| 
はい。
 a| 
はい。



 a| 
管理の簡易化
 a| 
○：ホットスペアやRAID設定の構成は不要
 a| 
×：ホットスペアを割り当ててRAIDを設定する必要があります



 a| 
パフォーマンスの調整
 a| 
いいえ
 a| 
はい。

|===