---
permalink: sm-storage/functional-comparison-of-pools-and-volume-groups.html 
sidebar: sidebar 
keywords: function, purpose, pool, volume, group, same, objects, set, drives, logically, together, storage, array, create, host, access 
summary: プールとボリュームグループの機能と目的は同じです。どちらのオブジェクトも、ストレージアレイ内で論理的にグループ化されている一連のドライブであり、ホストがアクセス可能なボリュームを作成するために使用されます。 
---
= プールとボリュームグループの機能比較
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プールとボリュームグループの機能と目的は同じです。どちらのオブジェクトも、ストレージアレイ内で論理的にグループ化されている一連のドライブであり、ホストがアクセス可能なボリュームを作成するために使用されます。

次の表は、プールとボリュームグループのどちらがストレージニーズに適しているかを判断する際に役立ちます。

[cols="3*""]
|===
| 機能 | プール | ボリュームグループ 


 a| 
異なるRAIDレベルがサポートされています
 a| 
いいえ常にRAID 6。
 a| 
はい。RAID 0、1、10、5、6を使用可能。



 a| 
シンボリュームがサポートされています
 a| 
はい。
 a| 
いいえ



 a| 
Full Disk Encryption（FDE）がサポートされる
 a| 
はい。
 a| 
はい。



 a| 
Data Assurance（DA）がサポートされています
 a| 
はい。
 a| 
はい。



 a| 
シェルフ損失の保護がサポートされます
 a| 
はい。
 a| 
はい。



 a| 
ドロワー損失の保護がサポートされます
 a| 
はい。
 a| 
はい。



 a| 
ドライブ速度混在のサポート
 a| 
同じにすることを推奨しますが、必須ではありません。一番低速のドライブにすべてのドライブの速度が合わせられます。
 a| 
同じにすることを推奨しますが、必須ではありません。一番低速のドライブにすべてのドライブの速度が合わせられます。



 a| 
ドライブ容量混在がサポートされています
 a| 
同じにすることを推奨しますが、必須ではありません。一番容量の少ないドライブにすべてのドライブの容量が合わせられます。
 a| 
同じにすることを推奨しますが、必須ではありません。一番容量の少ないドライブにすべてのドライブの容量が合わせられます。



 a| 
最小ドライブ数
 a| 
11.
 a| 
RAIDレベルによって異なります。RAID 0には1本必要RAID 1または10には2本（偶数）必要。RAID 5の最小数は3RAID 6の最小数は5



 a| 
ドライブの最大数
 a| 
ストレージアレイの上限まで
 a| 
RAID 1および10：ストレージアレイのRAID 5、6～30ドライブの最大数



 a| 
ボリュームの作成時に個々のドライブを選択できます
 a| 
いいえ
 a| 
はい。



 a| 
ボリュームの作成時にセグメントサイズを指定可能
 a| 
はい。128Kをサポート。
 a| 
はい。



 a| 
ボリュームの作成時にI/O特性を指定できます
 a| 
いいえ
 a| 
はい。ファイルシステム、データベース、マルチメディア、カスタムをサポート。



 a| 
ドライブ障害からの保護
 a| 
プール内の各ドライブの予約済み容量を使用し、再構築にかかる時間を短縮。
 a| 
ホットスペアドライブを使用します。再構築はドライブのIOPSによって制限されます。



 a| 
容量制限に達したときの警告
 a| 
はい。使用済み容量が最大容量の一定の割合に達したときにアラートを設定できる。
 a| 
いいえ



 a| 
別のストレージアレイへの移行をサポート
 a| 
いいえ最初にボリュームグループに移行する必要があります。
 a| 
はい。



 a| 
動的セグメントサイズ（DSS）
 a| 
いいえ
 a| 
はい。



 a| 
RAIDレベルを変更できます
 a| 
いいえ
 a| 
はい。



 a| 
ボリュームの拡張（容量の拡張）
 a| 
はい。
 a| 
はい。



 a| 
容量の拡張（容量の追加）
 a| 
はい。
 a| 
はい。



 a| 
容量の削減
 a| 
はい。
 a| 
いいえ

|===
[NOTE]
====
ドライブタイプ（HDD、SSD）の混在は、プールでもボリュームグループでもサポートされていません。

====