---
permalink: sm-storage/what-is-the-default-cluster.html 
sidebar: sidebar 
keywords: default, cluster, system, defined, entity, allow, unassociated, host, bus, adapter, port, identifier, logged, storage, array, gain, access, volumes, assign, physically, installed, particular 
summary: デフォルトクラスタはシステム定義のエンティティです。ストレージアレイにログインしたホストバスアダプタ（HBA）ホストポート識別子がホストに関連付けられていない場合、そのポートはデフォルトクラスタに割り当てられているボリュームへのアクセスを許可されます。ホストに関連付けられていないホストポート識別子は、ホストに物理的に搭載されてストレージアレイにログインしているが、特定のホストに論理的に関連付けられていないホストポートです。 
---
= デフォルトクラスタとは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
デフォルトクラスタはシステム定義のエンティティです。ストレージアレイにログインしたホストバスアダプタ（HBA）ホストポート識別子がホストに関連付けられていない場合、そのポートはデフォルトクラスタに割り当てられているボリュームへのアクセスを許可されます。ホストに関連付けられていないホストポート識別子は、ホストに物理的に搭載されてストレージアレイにログインしているが、特定のホストに論理的に関連付けられていないホストポートです。

[NOTE]
====
ホストがストレージアレイ内の特定のボリュームにアクセスできるようにする場合は、デフォルトクラスタを使用する_は_しない_選択します。代わりに、ホストポート識別子を対応するホストに関連付ける必要があります。この作業は、ホスト作成時にSystem Managerを使用して手動で実行するか、各ホストにインストールされているHost Context Agent（HCA）を使用して自動的に実行できます。その後、ボリュームを個々のホストまたはホストクラスタに割り当てます。

====
デフォルトクラスタは、すべてのホストとストレージアレイに接続されたすべてのログイン済みホストポート識別子がすべてのボリュームにアクセスできるようにするための外部ストレージ環境を構築する場合にのみ使用してください（フルアクセスモード） 特に、ホストをストレージアレイまたはSystem Managerで認識させません。

最初にボリュームをデフォルトクラスタに割り当てる際には、コマンドラインインターフェイス（CLI）を使用する必要があります。ただし、ボリュームを少なくとも1つデフォルトクラスタに割り当てるとSystem Managerに表示され、System Managerで管理できるようになります。
