---
permalink: sm-mirroring/change-role-between-volumes-in-a-mirrored-pair.html 
sidebar: sidebar 
keywords: perform, role, two, volumes, mirror, participation, synchronous, administration, event, disaster, local, storage, array 
summary: 同期ミラーリング対象のミラーペアに含まれる2つのボリューム間でロールを交換することができます。ミラーペアに含まれるボリューム間でのロールの変更は、管理目的、またはローカルストレージアレイで災害が発生した場合に行います。 
---
= ミラーペア内のボリューム間でロールを変更します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
同期ミラーリング対象のミラーペアに含まれる2つのボリューム間でロールを交換することができます。ミラーペアに含まれるボリューム間でのロールの変更は、管理目的、またはローカルストレージアレイで災害が発生した場合に行います。

.このタスクについて
プライマリボリュームをセカンダリロールに降格するか、またはセカンダリボリュームをプライマリロールに昇格することができます。プライマリボリュームにアクセスしているホストには、そのボリュームへの読み取り/書き込みアクセスが許可されます。プライマリボリュームがセカンダリボリュームになった場合、プライマリコントローラによって開始されたリモート書き込みだけがそのボリュームに書き込まれます。

.手順
. メニューを選択*：Storage [Synchronous Mirroring]*。
. ロールを変更するボリュームが含まれているミラーペアを選択し、*メニュー：その他[ロールの変更].*を選択します
+
確認メッセージが表示されます。

. ボリュームのロールを変更することを確認し、*ロールの変更*を選択します。
+
[NOTE]
====
ローカルストレージアレイがリモートストレージアレイと通信できない場合、ロールの変更が要求されたときに「ストレージアレイに接続できません」という*ダイアログボックスが表示されますが、リモートストレージアレイに接続できません。[はい]をクリックして、強制的にロールを変更します。

====


.結果
System Managerは次の処理を実行します。

* ミラーペア内の関連付けられているボリュームにアクセスできる場合は、ボリューム間でロールを変更します。選択した内容に応じて、System Managerはミラーペアのセカンダリボリュームのロールをプライマリに昇格するか、またはプライマリボリュームのロールをセカンダリに降格します。

