---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: configure, storage, array, administrator, password, protect, unauthorize, access 
summary: ストレージアレイには、不正なアクセスを防ぐために管理者パスワードを設定する必要があります。 
---
= 管理者パスワードによる保護
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイには、不正なアクセスを防ぐために管理者パスワードを設定する必要があります。



== 管理者パスワードの設定

管理者パスワードを設定すると、偶然または悪意を持ってシステムの停止を招くコマンドを実行するユーザからストレージアレイを保護できます。管理者パスワードは、System Managerを初めて起動するときに設定する必要があります。

すべてのユーザで共有する管理者パスワードが1つあります。このパスワードを使用するユーザは、オブジェクトや設定の追加、変更、削除など、ストレージアレイの設定を変更できます。



== パスワードを入力します

1つの管理セッションでパスワードの入力を求められるのは1回のみです。操作を行わないまま20分が経過するとセッションはタイムアウトし、その時点でパスワードをもう一度入力する必要があります。

セッション中に別の管理クライアントから同じストレージアレイを管理している別のユーザがパスワードを変更した場合は、次回の設定処理や表示処理でパスワードの入力を求められます。

セキュリティ上の理由から、パスワードの入力を試行できるのは5回までとなっており、この回数を超えるとストレージアレイは「ロックアウト」状態になります。この状態のストレージアレイは以降のパスワード入力を拒否します。パスワードを再度入力するには、ストレージアレイが「通常」状態にリセットされるまで10分間待つ必要があります。



== パスワードで保護されたドライブを取り外しています

パスワードはストレージアレイ上の各ドライブの予約領域に保存されます。ストレージアレイからすべてのドライブを取り外すと、そのパスワードは使用できなくなります。この状況を修正するには、元のドライブの1つをストレージアレイに再度取り付けます。



== パスワード保護を解除しています

コマンドのパスワード保護が不要になった場合は、現在の管理者パスワードを入力し、新しいパスワードのテキストボックスを空白のままにします。

[NOTE]
====
ストレージアレイで設定コマンドを実行すると、原因 がデータ損失などの深刻な損害を受ける可能性があります。このため、ストレージアレイには常に管理者パスワードを設定する必要があります。セキュリティを強化するには、英数字15文字以上の管理者パスワードを使用してください。

====