---
permalink: sm-interface/setup-wizard-terminology.html 
sidebar: sidebar 
keywords: setup, wizard, apply, storage, array 
summary: ストレージアレイに関連するセットアップウィザードの用語を次に示します。 
---
= セットアップウィザードに関する用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するセットアップウィザードの用語を次に示します。

[cols="1a,3a"]
|===
| 期間 | 説明 


 a| 
アプリケーション
 a| 
アプリケーションは、Microsoft SQL ServerやMicrosoft Exchangeなどのソフトウェアプログラムです。



 a| 
アラート
 a| 
アラートは、ストレージアレイで発生した重要なイベントについて管理者に通知します。Eメール、SNMPトラップ、またはsyslogを使用してアラートを送信できます。



 a| 
AutoSupport
 a| 
AutoSupport 機能は、ストレージアレイの健常性を監視し、テクニカルサポートに自動ディスパッチを送信します。



 a| 
ハードウェア
 a| 
ストレージシステムハードウェアには、ストレージアレイ、コントローラ、およびドライブが含まれます。



 a| 
ホスト
 a| 
ホストは、ストレージアレイ上のボリュームにI/Oを送信するサーバです。



 a| 
オブジェクト
 a| 
オブジェクトとは、任意の論理または物理ストレージコンポーネントのことです。論理オブジェクトには、ボリュームグループ、プール、ボリュームがあります。物理オブジェクトには、ストレージアレイ、アレイコントローラ、ホスト、ドライブがあります。



 a| 
プール
 a| 
プールは、論理的にグループ化された一連のドライブです。プールを使用して、ホストにアクセス可能な 1 つ以上のボリュームを作成することができます。（ボリュームはプールまたはボリュームグループから作成します）。



 a| 
ボリューム
 a| 
ボリュームは、アプリケーション、データベース、およびファイルシステムがデータを格納するコンテナです。ホストがストレージアレイのストレージにアクセスするために作成される論理コンポーネントです。

ボリュームは、プールまたはボリュームグループの使用可能な容量から作成します。ボリュームごとに容量が定義されています。ボリュームが複数のドライブで構成される場合でも、ホスト側では1つの論理コンポーネントとして認識され、



 a| 
ボリュームグループ
 a| 
ボリュームグループは、同じ特性を持つボリュームのコンテナです。ボリュームグループごとに容量とRAIDレベルが定義されています。ボリュームグループを使用して、ホストにアクセス可能な1つ以上のボリュームを作成することができます。（ボリュームはボリュームグループまたはプールから作成します）。



 a| 
ワークロード
 a| 
ワークロードは、アプリケーションをサポートするストレージオブジェクトです。アプリケーションごとに1つ以上のワークロードまたはインスタンスを定義できます。一部のアプリケーションについては、特性が似たボリュームで構成されるように System Manager によってワークロードが設定されます。これらのボリューム特性は、ワークロードがサポートするアプリケーションのタイプに基づいて最適化されます。たとえば、Microsoft SQL Serverアプリケーションをサポートするワークロードを作成し、そのワークロード用のボリュームを作成すると、Microsoft SQL Serverをサポートするようにボリューム特性が最適化されます。

|===