---
permalink: sm-hardware/controller-terminology.html 
sidebar: sidebar 
keywords: controller, terms, storage, array 
summary: ストレージアレイに関連するコントローラの用語を次に示します。 
---
= コントローラの用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するコントローラの用語を次に示します。

[cols="1a,3a"]
|===
| コンポーネント | 説明 


 a| 
コントローラ
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、 System Manager の機能を実装します。



 a| 
コントローラシェルフ
 a| 
コントローラシェルフには、一連のドライブと1つ以上のコントローラキャニスターが搭載されています。コントローラキャニスターには、コントローラ、ホストインターフェイスカード（HIC）、バッテリが搭載されます。



 a| 
DHCP
 a| 
動的ホスト構成プロトコル（DHCP）は、インターネットプロトコル（IP）ネットワークでIPアドレスなどのネットワーク設定パラメータを動的に配布するために使用されるプロトコルです。



 a| 
DNS
 a| 
Domain Name System（DNS；ドメインネームシステム）は、インターネットまたはプライベートネットワークに接続されたデバイスの命名システムです。DNSサーバはドメイン名のディレクトリを保持し、IPアドレスに変換します。



 a| 
デュプレックス構成
 a| 
デュプレックスは、ストレージアレイ内に 2 台のコントローラモジュールを配置した構成です。デュプレックスシステムでは、コントローラ、論理ボリュームパス、およびディスクパスが完全に冗長化されます。一方のコントローラで障害が発生した場合、そのI/Oがもう一方のコントローラに引き継がれて可用性が維持されます。デュプレックスシステムでは、ファンと電源装置も冗長構成になっています。



 a| 
全二重/半二重接続
 a| 
全二重と半二重は、接続モードを指します。全二重モードでは、2つのデバイスが双方向で同時に通信できます。半二重モードでは、デバイスは一度に一方向で通信できます（一方のデバイスがメッセージを送信し、他方のデバイスがメッセージを受信します）。



 a| 
HIC
 a| 
ホストインターフェイスカード（ HIC ）は、コントローラキャニスターにオプションで取り付けることができます。コントローラに搭載されたホストポートのことをベースボードホストポートと呼び、HIC に搭載されたホストポートのことを HIC ポートと呼びます。



 a| 
ICMP PING応答
 a| 
Internet Control Message Protocol（ICMP）は、ネットワークに接続されたコンピュータのオペレーティングシステムでメッセージの送信に使用されるプロトコルです。ICMPメッセージを送信することで、ホストに到達できるかどうかや、そのホストとのパケットの送受信にどれくらいの時間がかかるかが確認されます。



 a| 
MAC アドレス
 a| 
メディアアクセス制御（MAC）アドレスはイーサネットで使用される識別子で、同じ物理トランスポートネットワークインターフェイス上の2つのポートを接続する別々の論理チャネルを区別します。



 a| 
管理クライアント
 a| 
管理クライアントは、System Managerにアクセスするためのブラウザがインストールされたコンピュータです。



 a| 
MTU
 a| 
Maximum Transmission Unit（MTU；最大転送単位）は、ネットワークで送信可能なパケットまたはフレームの最大サイズです。



 a| 
NTP
 a| 
Network Time Protocol（NTP；ネットワークタイムプロトコル）は、データネットワーク内のコンピュータシステム間でクロック同期を行うためのネットワークプロトコルです。



 a| 
シンプレックス構成です
 a| 
シンプレックスは、ストレージアレイ内に1つのコントローラモジュールを配置した構成です。シンプレックスシステムでは、コントローラやディスクパスは冗長化されませんが、ファンと電源装置は冗長構成になります。



 a| 
VLAN
 a| 
仮想ローカルエリアネットワーク（VLAN）は、同じデバイス（スイッチやルータなど）でサポートされる他のネットワークと物理的に分離されているかのように動作する論理ネットワークです。

|===