---
permalink: sm-hardware/erase-drive.html 
sidebar: sidebar 
keywords: erase, secure, enabled, drive, reuse, volume, group, pool, ssd cache, storage array 
summary: セキュリティ有効ドライブを消去して、別のボリュームグループ、プール、SSDキャッシュ、または別のストレージアレイで再利用することができます。この手順 は、ドライブのセキュリティ属性をリセットし、データを再度読み取ることができないようにします。 
---
= セキュリティ有効ドライブを消去します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティ有効ドライブを消去して、別のボリュームグループ、プール、SSDキャッシュ、または別のストレージアレイで再利用することができます。この手順 はドライブのセキュリティ属性をリセットし、データを二度と読み取れないようにします。

.作業を開始する前に
セキュリティ有効ドライブの状態は未割り当てである必要があります。

.このタスクについて
Secure Eraseオプションは、セキュリティ有効ドライブのすべてのデータを削除してドライブのセキュリティ属性をリセットする場合にのみ使用します。

[CAUTION]
====
*データ損失の可能性*-- Secure Erase操作を取り消すことはできません手順 で正しいドライブを選択していることを確認してください。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にコントローラが表示されている場合は、*シェルフの前面を表示*をクリックします。
+
図の表示が切り替わり、コントローラではなくドライブが表示されます。

. フィルタフィールドを使用して、シェルフ内のセキュリティ有効で未割り当てのドライブをすべて表示します。[Show drives that are ...*]ドロップダウン・リストから'[*Secure-enabled *]および[*Unassigned *]を選択します
+
[NOTE]
====
すべてのドライブが同じ物理属性を共有している場合、*次のドライブを表示する*フィルタフィールドは表示されません。すべてのドライブが同じ論理属性を共有している場合'ストレージ・アレイ*フィルタ・フィールドの* Anywhereは表示されません

シェルフビューには、セキュリティ有効で未割り当てのドライブのみが表示され、その他はすべてグレー表示になります。

====
. 消去するセキュリティ有効ドライブを選択します。
+
[CAUTION]
====
*データ損失の可能性*--正しいドライブを選択していることを確認してくださいSecure Erase操作の完了後は、データを回復できません。

====
+
ドライブのコンテキストメニューが開きます。

. 「* Secure Erase *」を選択します。
+
Secure Eraseオプションは、未割り当てのセキュア有効ドライブを選択した場合にのみ表示されます。

+
[NOTE]
====
NVMe SEDドライブの場合は、PSIDを指定する必要があります。PSIDはドライブラベルに記載されています。これは、バックアップのロックキーがない場合に必要です。

====
. Secure Erase Driveダイアログボックスで、データ損失に関する重要な情報を読みます。
. 操作を確定し、*消去*をクリックします。


.結果
これで、別のボリュームグループまたはディスクプール、あるいは別のストレージアレイでドライブを使用できるようになります。
