---
permalink: sm-hardware/hardware-terminology.html 
sidebar: sidebar 
keywords: hardware, terms, apply, storage 
summary: ストレージアレイに関連するハードウェアの用語を次に示します。 
---
= ハードウェアの用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するハードウェアの用語を次に示します。

[cols="1a,3a"]
|===
| コンポーネント | 説明 


 a| 
ストレージアレイ
 a| 
ストレージアレイには、シェルフ、コントローラ、ドライブ、ソフトウェア、およびファームウェアが含まれます。



 a| 
シェルフ
 a| 
シェルフは、キャビネットまたはラックに設置されるエンクロージャです。ストレージアレイのハードウェアコンポーネントを収容します。シェルフには、コントローラシェルフとドライブシェルフの 2 種類があります。コントローラシェルフは、コントローラとドライブを収容します。ドライブシェルフは、入出力モジュール（ IOM ）とドライブを収容します。



 a| 
コントローラ
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、 System Manager の機能を実装します。



 a| 
ドライブ
 a| 
ドライブは、データ用の物理ストレージメディアとして使用される電磁的な機械デバイスまたはソリッドステートメモリデバイスです。



 a| 
ベイ
 a| 
ベイは、ドライブやその他のコンポーネントを取り付けるシェルフのスロットです。



 a| 
ドライブシェルフ
 a| 
ドライブシェルフは、拡張シェルフとも呼ばれ、一連のドライブと2つの入出力モジュール（IOM）が搭載されます。IOMには、ドライブシェルフをコントローラシェルフまたはその他のドライブシェルフに接続するSASポートが搭載されています。

[NOTE]
====
ドライブシェルフはEF600ストレージシステムに対しては使用できません。

====


 a| 
コントローラシェルフ
 a| 
コントローラシェルフには、一連のドライブと1つ以上のコントローラキャニスターが搭載されています。コントローラキャニスターには、コントローラ、ホストインターフェイスカード（HIC）、バッテリが搭載されます。



 a| 
電源/ファンキャニスター
 a| 
電源 / ファンキャニスターは、シェルフに搭載されるアセンブリです。電源装置と一体型ファンで構成されます。



 a| 
IOM（ESM）
 a| 
IOMは、ドライブシェルフをコントローラシェルフに接続するためのSASポートを含む入出力モジュールです。

[NOTE]
====
ドライブシェルフはEF600ストレージシステムに対しては使用できません。

====
[NOTE]
====
以前のコントローラモデルでは、IOMは環境サービスモジュール（ESM）と呼ばれていました。

====


 a| 
SFP
 a| 
SFPは、Small Form-factor Pluggable（SFP）トランシーバです。

|===