---
permalink: sm-hardware/limit-the-drive-view.html 
sidebar: sidebar 
keywords: storage array, drives, different types, physical, logical, attributes, hardware, page, filter fields 
summary: ストレージアレイに物理属性と論理属性が異なるドライブが含まれている場合、ハードウェアページのフィルタフィールドを使用して、ドライブの表示を制限したり、特定のドライブを特定したりできます。 
---
= ドライブ表示を制限します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに物理属性と論理属性が異なるドライブが含まれている場合、ハードウェアページのフィルタフィールドを使用して、ドライブの表示を制限したり、特定のドライブを特定したりできます。

ドライブフィルタを使用すると、特定のセキュリティ属性（セキュリティ対応など）で、特定の論理的場所（ボリュームグループ1など）にある特定のタイプの物理ドライブ（すべてのSASなど）のみに絞って表示することができます。これらのフィルタは、一緒に使用することも、個別に使用することもでき

[NOTE]
====
すべてのドライブが同じ物理属性を共有している場合、*次のドライブを表示する*フィルタフィールドは表示されません。すべてのドライブが同じ論理属性を共有している場合'ストレージ・アレイ*フィルタ・フィールドの* Anywhereは表示されません

====
.手順
. 「 * ハードウェア * 」を選択します。
. 最初のフィルタフィールド（* Show drives that are ...*）で、ドロップダウン矢印をクリックして、使用可能なドライブタイプとセキュリティ属性を表示します。
+
ドライブタイプには次のものがあります。

+
** ドライブのメディアタイプ（SSD、HDD）
** ドライブのインターフェイスタイプ（SAS、NVMe）
** ドライブの容量（最大から最小）
** セキュリティ属性には次のようなものがあります（ドライブ速度（最大から最小）。
** セキュリティ対応
** セキュリティ有効
** DA（Data Assurance）対応ドライブがすべて同じ場合、ドロップダウンリストに表示されません。たとえば、ストレージアレイに含まれているすべてのSSDドライブが、SASインターフェイスを備えた速度15000RPMのSSDドライブで、一部のSSDの容量が異なる場合、ドロップダウンリストには、容量のみがフィルタリングの選択肢として表示されます。


+
フィールドでオプションを選択すると、フィルタ条件に一致しないドライブは、グラフィカルビューでグレー表示されます。

. 2番目のフィルタボックスで、ドロップダウン矢印をクリックして、ドライブの使用可能な論理的場所を表示します。
+
[NOTE]
====
フィルタ条件をクリアする必要がある場合は、フィルタボックスの右端にある[*Clear*]を選択します。

====
+
論理的な場所には次のものがあり

+
** プール
** ボリュームグループ
** ホットスペア
** SSD キャッシュ
** Unassigned：フィールドからオプションを選択すると、フィルタ条件に一致しないドライブはグラフィカルビューでグレー表示されます。


. *オプション：*フィルタフィールドの右端でロケーターライトを点灯*を選択すると、表示されたドライブのロケーターライトを点灯できます。
+
この操作は、ストレージアレイ内でドライブの場所を特定する際に役立ちます。


