---
permalink: sm-hardware/unlock-or-reset-a-locked-nvme-drive.html 
sidebar: sidebar 
keywords: insert, lock, nvme, storage array, key file, psid, security key, drive data 
summary: ロックされたNVMeドライブをストレージアレイに挿入する場合、ドライブに関連付けられたセキュリティキーファイルを追加することでドライブデータのロックを解除できます。セキュリティキーがない場合、ドライブの物理セキュリティID（PSID）を入力してロックされた各NVMeドライブでリセットを実行し、セキュリティ属性をリセットしてドライブデータを消去できます。 
---
= ロックされたNVMeドライブのロックを解除またはリセットします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ロックされたNVMeドライブをストレージアレイに挿入する場合、ドライブに関連付けられたセキュリティキーファイルを追加することでドライブデータのロックを解除できます。セキュリティキーがない場合、ドライブの物理セキュリティID（PSID）を入力してロックされた各NVMeドライブでリセットを実行し、セキュリティ属性をリセットしてドライブデータを消去できます。

.作業を開始する前に
* ロックを解除する場合は、管理クライアント（System Managerへのアクセスに使用するブラウザを備えたシステム）にセキュリティキーファイル（拡張子は「.slk」）があることを確認します。キーに関連付けられているパスフレーズも必要です。
* リセットする場合は、リセットする各ドライブのPSIDを確認する必要があります。PSIDを確認するには、ドライブを物理的に取り外し、ドライブのラベルに記載されたPSID（最大32文字）を確認してから、ドライブを再度取り付けます。


このタスクでは、セキュリティキーファイルをストレージアレイにインポートして、NVMeドライブのデータのロックを解除する方法について説明します。セキュリティキーがない状況では、ロックされたドライブでリセットを実行する方法についても説明します。

[NOTE]
====
外部キー管理サーバを使用してドライブがロックされている場合は、System Managerで* MENU：Settings（システム）> Security key management（セキュリティキー管理）*を選択し、外部キー管理を設定してドライブのロックを解除します。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にコントローラが表示されている場合は、*シェルフの前面を表示*をクリックします。
+
図の表示が切り替わり、コントローラではなくドライブが表示されます。

. ロックを解除またはリセットするNVMeドライブを選択します。
+
ドライブのコンテキストメニューが開きます。

. セキュリティー・キー・ファイルを適用するには、*ロック解除*を選択します。セキュリティー・キー・ファイルがない場合は、*リセット*を選択します。
+
これらのオプションは、ロックされたNVMeドライブを選択した場合にのみ表示されます。

+
[CAUTION]
====
リセット処理を実行すると、すべてのデータが消去されます。リセットは、セキュリティキーがない場合にのみ実行してください。ロックされたドライブをリセットすると、ドライブ上のすべてのデータが完全に削除され、セキュリティ属性が「セキュリティ対応」にリセットされますが、有効になりません。*この操作は元に戻せません。*

====
. 次のいずれかを実行します。
+
.. *ロック解除*：[セキュアドライブのロック解除]ダイアログボックスで、[*参照]をクリックし、ロック解除するドライブに対応するセキュリティキーファイルを選択します。次に、パスフレーズを入力し、*ロック解除*をクリックします。
.. *リセット*: Reset Locked Driveダイアログボックスで、フィールドにPSID文字列を入力し、「reset」と入力して確定します。[*リセット*]をクリックします。
+
ロック解除の場合、1回の処理ですべてのNVMeドライブのロックを解除できます。リセットの場合は、リセットするドライブを個別に選択する必要があります。





これで、別のボリュームグループまたはディスクプール、あるいは別のストレージアレイでNVMeドライブを使用できるようになります。
