---
permalink: um-manage/discover-multiple-arrays.html 
sidebar: sidebar 
keywords: discover, multiple, storage, arrays, 
summary: 複数のアレイの検出では、管理サーバが配置されているサブネット全体からすべてのストレージアレイを検出し、検出されたアレイを管理ドメインに自動的に追加します。 
---
= 複数のストレージアレイを検出する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
複数のアレイの検出では、管理サーバが配置されているサブネット全体からすべてのストレージアレイを検出し、検出されたアレイを管理ドメインに自動的に追加します。

.このタスクについて
複数のアレイを検出するには、次の手順を実行します。



== 手順1：ネットワークアドレスを入力する

ローカルのサブネットワーク全体を検索するには、ネットワークアドレス範囲を入力します。到達したストレージアレイが* Discover *ページに表示され、管理ドメインに追加される可能性があります。

.このタスクについて
何らかの理由で検出操作を停止する必要がある場合は、*検出の停止*をクリックします。

.手順
. [* Manage *（管理）]ページで、[* Add/Discover*（追加/検出*）]を選択します。
+
ストレージアレイの追加と検出ダイアログが表示されます。

. [*ネットワーク範囲内のすべてのストレージアレイを検出する*]ラジオボタンを選択します。
. 開始ネットワークアドレスと終了ネットワークアドレスを入力して、ローカルサブネットワーク全体を検索し、*検出の開始*をクリックします。
+
検出プロセスが開始されます。この検出プロセスが完了するまでに数分かかることがあります。ストレージアレイが検出されると、* Discover *ページのテーブルにデータが表示されます。

+
[NOTE]
====
管理可能なアレイが検出されない場合は、ストレージアレイがネットワークに適切に接続されていて、割り当てられたアドレスが範囲内にあることを確認してください。「*新しい検出パラメータ*」をクリックして、「*追加/検出*」ページに戻ります。

====
. 検出されたストレージアレイのリストを確認します。
. 管理ドメインに追加するストレージアレイの横にあるチェックボックスをオンにし、[*次へ*]をクリックします。
+
管理ドメインに追加する各アレイについて、SANtricity Unified Managerでクレデンシャルのチェックが実行されます。そのアレイに関連付けられている自己署名証明書や信頼されていない証明書の解決が必要になる場合があります。

. 「 * 次へ * 」をクリックして、ウィザードの次の手順に進みます。
. に進みます <<手順2：検出時に自己署名証明書を解決する>>。




== 手順2：検出時に自己署名証明書を解決する

検出プロセスでは、ストレージアレイに信頼できるソースからの証明書があるかどうかが確認されます。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。


.手順
. 次のいずれかを実行します。
+
** 検出されたストレージアレイへの接続を信頼する場合は、ウィザードの次のカードに進みます。自己署名証明書は信頼済みとしてマークされ、SANtricity Unified Managerにストレージアレイが追加されます。
** ストレージアレイへの接続を信頼しない場合は、*キャンセル*を選択し、各ストレージアレイのセキュリティ証明書戦略を検証してからUnified Managerに追加してください。


. 「 * 次へ * 」をクリックして、ウィザードの次の手順に進みます。
. に進みます <<手順3：検出時に信頼されていない証明書を解決する>>。




== 手順3：検出時に信頼されていない証明書を解決する

信頼されていない証明書の問題は、ストレージアレイからSANtricity Unified Managerへのセキュアな接続を確立しようとしたときに、接続がセキュアであることが確認できないと発生します。アレイの検出プロセスでは、信頼されていない証明書を解決するために、信頼できる第三者機関が発行した認証局（CA）証明書（CA署名証明書）をインポートします。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。
* ストレージアレイの各コントローラの証明書署名要求（.CSRファイル）を生成してCAに送信しておく必要があります。
* 信頼された証明書ファイルをCAから受け取っておきます。
* 証明書ファイルがローカルシステム上にある必要があります。


.このタスクについて
信頼された追加のCA証明書のインストールが必要になる可能性があるのは、次のいずれかに該当する場合です。

* ストレージアレイを新たに追加した。
* 一方または両方の証明書の期限が切れている。
* 一方または両方の証明書が失効している。
* 一方または両方の証明書のルート証明書または中間証明書がない。


.手順
. 信頼されていない証明書を解決するストレージアレイの横にあるチェックボックスを選択し、* Import *ボタンを選択します。
+
信頼された証明書ファイルをインポートするためのダイアログボックスが表示されます。

. Browse（参照）*をクリックして、ストレージアレイの証明書ファイルを選択します。
+
ダイアログボックスにファイル名が表示されます。

. [* インポート * ] をクリックします。
+
ファイルがアップロードされて検証されます。

+
[NOTE]
====
信頼されていない証明書の問題が未解決のストレージアレイはUnified Managerに追加されません。

====
. 「 * 次へ * 」をクリックして、ウィザードの次の手順に進みます。
. に進みます <<手順4：パスワードを入力する>>。




== 手順4：パスワードを入力する

管理ドメインに追加するストレージアレイのパスワードを入力する必要があります。

.作業を開始する前に
* ストレージアレイが正しくセットアップおよび設定されている必要があります。
* ストレージアレイのパスワードは、SANtricity システムマネージャの*アクセス管理*タイルを使用して設定する必要があります。


.手順
. SANtricity Unified Managerに追加する各ストレージアレイのパスワードを入力します。
. *オプション：*ストレージアレイをグループに関連付けます。ドロップダウンリストから、選択したストレージアレイを関連付ける目的のグループを選択します。
. [ 完了 ] をクリックします。


.完了後
ストレージアレイが管理ドメインに追加され、指定した場合は選択したグループに関連付けられます。

[NOTE]
====
Unified Managerから指定のストレージアレイへの接続が確立されるまでに数分かかることがあります。

====