---
permalink: um-manage/discover-single-array.html 
sidebar: sidebar 
keywords: discover, single, array, 
summary: 単一ストレージアレイの追加/検出オプションを使用して、組織のネットワークを手動で検出して追加します。 
---
= 単一のアレイを検出します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
単一ストレージアレイの追加/検出オプションを使用して、ストレージアレイを手動で検出し、組織のネットワークに追加します。

.作業を開始する前に
* ストレージアレイが正しくセットアップおよび設定されている必要があります。
* ストレージアレイのパスワードは、SANtricity システムマネージャのアクセス管理タイルを使用して設定する必要があります。


.手順
. [* Manage *（管理）]ページで、[* Add/Discover*（追加/検出*）]を選択します。
+
[ストレージアレイの追加/検出*]ダイアログボックスが表示されます。

. [Discover a single storage array]オプションボタンを選択します。
. ストレージアレイ内のいずれかのコントローラのIPアドレスを入力し、*検出の開始*をクリックします。
+
SANtricity Unified Managerから指定のストレージアレイへの接続に数分かかることがあります。

+
[NOTE]
====
指定したコントローラのIPアドレスに接続できない場合、「*ストレージアレイにアクセスできません」というメッセージが表示されます。

====
. プロンプトが表示されたら、自己署名証明書を解決します。
+
検出プロセスでは、検出されたストレージアレイに信頼できるソースからの証明書があるかどうかが確認されます。ストレージアレイのデジタル証明書が見つからない場合、承認された認証局（CA）の署名がない証明書について、セキュリティ例外を追加して解決するように求められます。

. 信頼されていない証明書についての確認が求められたら解決し
+
信頼されていない証明書の問題は、ストレージアレイからSANtricity Unified Managerへのセキュアな接続を確立しようとしたときに、接続がセキュアであることが確認できないと発生します。信頼されていない証明書を解決するには、信頼できる第三者機関から発行された認証局（CA）証明書をインポートします。

. 「 * 次へ * 」をクリックします。
. *オプション：*検出されたストレージアレイをグループに関連付けます。ドロップダウンリストから、ストレージアレイを関連付ける目的のグループを選択します。
+
デフォルトでは、「すべて」のグループが選択されています。

. 管理ドメインに追加するストレージアレイの管理者パスワードを入力し、* OK *をクリックします。


ストレージアレイがSANtricity Unified Managerに追加され、指定した場合は選択したグループにも追加されます。

サポートデータの自動収集が有効になっている場合は、追加したストレージアレイのサポートデータが自動的に収集されます。
