---
permalink: um-manage/import-system-settings.html 
sidebar: sidebar 
keywords: import, system, settings, 
summary: ストレージアレイから別のストレージアレイにシステム設定をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。 
---
= システム設定をインポートします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイから別のストレージアレイにシステム設定をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。

.作業を開始する前に
* ソースとして使用するストレージアレイのシステム設定をSANtricity System Managerで設定しておきます。
* ターゲットストレージアレイの既存の構成は、SANtricity システムマネージャでバックアップされます（メニュー：[設定（Settings）][システム（System）]>[ストレージアレイ構成の保存（Save Storage Array Configuration）]）。


.このタスクについて
インポートされる設定には、ボリュームのメディアスキャン設定、コントローラのSSD設定、および自動ロードバランシングが含まれます（ホスト接続レポートは含まれません）。

.手順
. [*管理*]ページで、[*設定のインポート*]をクリックします。
+
設定のインポート*ウィザードが開きます。

. [設定の選択*]ダイアログで、[システム*]を選択し、[次へ*]をクリックします。
+
ソースアレイを選択するためのダイアログボックスが開きます。

. 「*ソースの選択*」ダイアログで、インポートする設定のアレイを選択し、「*次へ*」をクリックします。
. [ターゲットの選択*]ダイアログで'新しい設定を受信する1つまたは複数のアレイを選択します
+
[NOTE]
====
ファームウェアが8.50未満のストレージアレイは選択できません。また、Unified Managerが通信できないアレイ（オフラインのアレイや、証明書、パスワード、ネットワークに問題があるアレイなど）は、このダイアログに表示されません。

====
. [ 完了 ] をクリックします。
+
[*オペレーション*（Operations *）]ページには、インポート操作の結果が表示されます。処理が失敗した場合は、その行をクリックすると詳細を確認できます。



.結果
ターゲットストレージアレイのシステム設定がソースアレイと同じに設定されます。
