---
permalink: um-manage/import-storage-configuration-settings.html 
sidebar: sidebar 
keywords: import, storage, configuration, settings, 
summary: ストレージアレイから別のストレージアレイにストレージ構成をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。 
---
= ストレージ構成の設定をインポートします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイから別のストレージアレイにストレージ構成をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。

.作業を開始する前に
* ソースとして使用するストレージアレイのストレージをSANtricity System Managerで設定しておきます。
* ターゲットストレージアレイの既存の構成は、SANtricity システムマネージャでバックアップされます（メニュー：[設定（Settings）][システム（System）]>[ストレージアレイ構成の保存（Save Storage Array Configuration）]）。
* ソースアレイとターゲットアレイが次の要件を満たしている必要があります。
+
** コントローラが配置されているシェルフが同じである必要があります。
** シェルフIDが同じである必要があります。
** 拡張シェルフの同一のスロットに同じドライブタイプが搭載されている。
** RBODエンクロージャタイプが同一である。
** HICが、ホストのData Assurance機能を含めて同一である。
** ターゲットアレイのステータスが最適lである必要があります。
** ターゲットアレイのボリューム容量がソースアレイよりも大きい。


* 次の制限事項を理解しておきます。
+
** デュプレックス構成からシンプレックス構成へのインポートはサポートされていませんが、シンプレックス構成からデュプレックス構成へのインポートは可能です。
** ソースアレイのディスクプールのボリュームが64TB以上の場合、ターゲットでインポートプロセスを実行できない。
** シンボリュームはインポートプロセスに含まれません。




インポートされる設定には、設定済みのボリューム（リポジトリボリュームでないシックボリュームのみ）、ボリュームグループ、プール、およびホットスペアドライブの割り当てが含まれます。

.手順
. [*管理*]ページで、[*設定のインポート*]をクリックします。
+
設定のインポート*ウィザードが開きます。

. [設定の選択*]ダイアログで、[ストレージ構成*]を選択し、[次へ*]をクリックします。
+
ソースアレイを選択するためのダイアログボックスが開きます。

. 「*ソースの選択*」ダイアログで、インポートする設定のアレイを選択し、「*次へ*」をクリックします。
. [ターゲットの選択*]ダイアログで'新しい設定を受信する1つまたは複数のアレイを選択します
+
[NOTE]
====
ファームウェアが8.50未満のストレージアレイは選択できません。また、Unified Managerが通信できないアレイ（オフラインのアレイや、証明書、パスワード、ネットワークに問題があるアレイなど）は、このダイアログに表示されません。

====
. [ 完了 ] をクリックします。
+
[*オペレーション*（Operations *）]ページには、インポート操作の結果が表示されます。処理が失敗した場合は、その行をクリックすると詳細を確認できます。



ターゲットストレージアレイのストレージ構成がソースアレイと同じに設定されます。
