---
permalink: um-manage/import-alert-settings.html 
sidebar: sidebar 
keywords: import, alert, settings, 
summary: ストレージアレイから別のストレージアレイにアラート設定をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。 
---
= アラート設定をインポートします
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイから別のストレージアレイにアラート設定をインポートできます。このバッチ処理により、ネットワーク内に複数のアレイを設定する必要がある場合に時間を節約できます。

.作業を開始する前に
* アラートは、ソースとして使用するストレージアレイのSANtricity System Managerで設定します（メニュー：設定[アラート]）。
* ターゲットストレージアレイの既存の構成は、SANtricity システムマネージャでバックアップされます（メニュー：[設定（Settings）][システム（System）]>[ストレージアレイ構成の保存（Save Storage Array Configuration）]）。


インポート処理では、Eメール、SNMP、またはsyslogのいずれかのアラートを選択できます。インポートされる設定は次のとおりです。

* *Email alerts *--メールサーバのアドレスとアラート受信者の電子メールアドレス。
* *Syslogアラート*-- syslogサーバのアドレスとUDPポート。
* *snmp alerts *-- SNMPサーバのコミュニティ名とIPアドレス。


.手順
. [*管理*]ページで、[*設定のインポート*]をクリックします。
+
設定のインポート*ウィザードが開きます。

. [*設定の選択*]ダイアログで、[*電子メールアラート*]、[* SNMPアラート*]、または[* syslogアラート*]のいずれかを選択し、[*次へ*]をクリックします。
+
ソースアレイを選択するためのダイアログボックスが開きます。

. 「*ソースの選択*」ダイアログで、インポートする設定のアレイを選択し、「*次へ*」をクリックします。
. [ターゲットの選択*]ダイアログで'新しい設定を受信する1つまたは複数のアレイを選択します
+
[NOTE]
====
ファームウェアが8.50未満のストレージアレイは選択できません。また、Unified Managerが通信できないアレイ（オフラインのアレイや、証明書、パスワード、ネットワークに問題があるアレイなど）は、このダイアログに表示されません。

====
. [ 完了 ] をクリックします。
+
[*オペレーション*（Operations *）]ページには、インポート操作の結果が表示されます。処理が失敗した場合は、その行をクリックすると詳細を確認できます。



Eメール、SNMP、またはsyslogを使用して管理者にアラートを送信するようにターゲットストレージアレイが設定されます。
