---
permalink: sm-settings/add-trap-destinations-for-snmp-alerts.html 
sidebar: sidebar 
keywords: ten server, snmp traps, sending 
summary: SNMPトラップの送信に使用するサーバは最大10台まで追加できます。 
---
= SNMPアラートのトラップ送信先を追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMPトラップの送信に使用するサーバは最大10台まで追加できます。

.作業を開始する前に
* 追加するネットワークサーバにSNMPサービスアプリケーションが設定されている必要があります。イベントモニタからトラップメッセージを送信するためには、このサーバのネットワークアドレス（IPv4アドレスまたはIPv6アドレス）が必要です。複数のサーバを使用できます（最大10台のサーバを使用できます）。
* 印刷可能なASCII文字だけを使用したコミュニティ名が作成されている必要があります。コミュニティ名は、ネットワークサーバのパスワードのような役割を果たす文字列で、通常はネットワーク管理者が作成します。コミュニティを最大256個作成できます。
* SNMPサービスアプリケーションがインストールされたサーバに管理情報ベース（MIB）ファイルをコピーしてコンパイルしておきます。このMIBファイルは、監視および管理されるデータを定義します。
+
MIBファイルがない場合は、ネットアップサポートサイトから入手できます。

+
** に進みます https://mysupport.netapp.com/site/["ネットアップサポート"^]。
** 「*ダウンロード」をクリックします。
** [*ソフトウェア]をクリックします。
** 管理ソフトウェア（SANtricity System Managerなど）を探し、右側の「* Go！*」をクリックします。
** 最新バージョンで* View & Download *をクリックします。
** ページの下部にある[* Continue *（続行）]をクリックします。
** EULA に同意します。
** 下にスクロールしてSNMPトラップのMIBファイル*を探し、リンクをクリックしてファイルをダウンロードします。




.手順
. [*設定*>*警告*]を選択します。
. [*SNMP*]タブを選択します。
+
現在定義されているトラップ送信先が表に表示されます。

. 「トラップのディスペションを追加」*を選択します。
+
トラップ送信先の追加ダイアログボックスが開きます。

. 1つ以上のトラップ送信先を入力し、関連するコミュニティ名を選択して、* Add *をクリックします。
+
** *Trap Destination*-- SNMPサービスを実行しているサーバーのIPv4またはIPv6アドレスを入力します
** *コミュニティ名*--ドロップダウンから、このトラップの送信先のコミュニティ名を選択します。（コミュニティ名を1つだけ定義した場合は、その名前がこのフィールドにすでに表示されます）。
** *認証失敗トラップを送信*--コミュニティ名が認識されないためにSNMP要求が拒否された場合にトラップの送信先にアラートを送信するには、このオプション（チェックボックス）を選択します。「*追加」をクリックすると、トラップの送信先と関連するコミュニティ名が表に表示されます。


. トラップが有効であることを確認するには、テーブルからトラップの送信先を選択し、*トラップの送信先のテスト*をクリックして、設定したアドレスにテストトラップを送信します。


アラート対象のイベントが発生するたびに、イベントモニタからサーバにSNMPトラップが送信されます。
