---
permalink: sm-settings/back-up-security-key.html 
sidebar: sidebar 
keywords: security key, changing, creating, backup, copy, original, corrupted 
summary: セキュリティキーの作成後または変更後に、元のキーが破損した場合に備えてキーファイルのバックアップコピーを作成することができます。 
---
= セキュリティキーをバックアップする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティキーの作成後または変更後に、元のキーが破損した場合に備えてキーファイルのバックアップコピーを作成することができます。

.作業を開始する前に
* セキュリティキーがすでに存在している必要があります。


このタスクでは、以前に作成したセキュリティキーをバックアップする方法について説明します。この手順 では、バックアップ用の新しいパスフレーズを作成します。このパスフレーズは、元のキーの作成時または最後の変更時に使用されたパスフレーズと同じである必要はありません。このパスフレーズは、作成するバックアップにのみ適用されます。

.手順
. 「* MENU（*メニュー）」：「Settings（設定）」[ System（システム）
. セキュリティキー管理*で、*バックアップキー*を選択します。
+
[セキュリティキーのバックアップ]ダイアログボックスが開きます。

. [*パスフレーズを定義/パスフレーズを再入力*]フィールドに、このバックアップのパスフレーズを入力して確認します。
+
8~32文字で指定し、以下の文字をそれぞれ1文字以上含める必要があります。

+
** 大文字のアルファベット（1文字以上）
** 数字（1文字以上）
** アルファベット以外の文字（！、*、@など）（1文字以上）


+
[CAUTION]
====
あとで使用できるように、エントリを記録しておいてください。このセキュリティキーのバックアップにアクセスするには、パスフレーズが必要です。

====
. [バックアップ]をクリックします。
+
セキュリティキーのバックアップがローカルホストにダウンロードされ、[*Confirm/Record Security Key Backup*]ダイアログボックスが開きます。

+
[NOTE]
====
ダウンロードしたセキュリティキーファイルのパスは、ブラウザのデフォルトのダウンロード先によって異なる場合があります。

====
. パスフレーズを安全な場所に記録し、*閉じる*をクリックします。


バックアップセキュリティキーを検証する必要があります。
