---
permalink: sm-settings/change-security-key.html 
sidebar: sidebar 
keywords: replace, security key, new key, potential, security, breach, unauthorized, personnel, data 
summary: セキュリティキーは、いつでも新しいキーに置き換えることができます。セキュリティキーの変更が必要になるのは、会社でセキュリティ侵害が発生する可能性があり、権限のない担当者がドライブのデータにアクセスできないようにする場合です。 
---
= セキュリティキーを変更する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティキーは、いつでも新しいキーに置き換えることができます。社内でセキュリティ侵害の可能性があり、ドライブのデータへの不正アクセスを防ぎたい場合は、セキュリティキーの変更が必要になることがあります。

.作業を開始する前に
セキュリティキーがすでに存在している必要があります。

.このタスクについて
このタスクでは、セキュリティキーを変更し、新しいセキュリティキーに置き換える方法について説明します。この処理が完了すると、古いキーは無効になります。

.手順
. 「* MENU（*メニュー）」：「Settings（設定）」[ System（システム）
. セキュリティキー管理*で、*キーの変更*を選択します。
+
[セキュリティキーの変更]ダイアログボックスが開きます。

. 次のフィールドに情報を入力します。
+
** *セキュリティキー識別子を定義--*(内部セキュリティキーの場合のみ) デフォルト値（コントローラファームウェアで生成されたストレージアレイ名とタイムスタンプ）をそのまま使用するか、独自の値を入力します。入力できる文字数は最大189文字です。使用できるのは英数字のみで、スペース、句読点、記号は使用できません。
+
[NOTE]
====
入力した文字列の前後に追加の文字が自動的に生成されて付加されます。文字が追加されることで識別子が一意であることが保証されます。

====
** *パスフレーズを定義/パスフレーズを再入力*--これらの各フィールドにパスフレーズを入力します8~32文字で指定し、以下の文字をそれぞれ1文字以上含める必要があります。
+
*** 大文字のアルファベット（1文字以上）。パスフレーズでは大文字と小文字が区別されることに注意してください。
*** 数字（1文字以上）。
*** 英数字以外の、！、*、@などの文字（1文字以上）。




+
[CAUTION]
====
この値はあとで使用するため必ずメモしておいてください。セキュリティ有効ドライブをストレージアレイから移動する必要がある場合、ドライブデータのロックを解除するために識別子とパスフレーズが必要になります。

====
. [ 変更（ Change ） ] をクリックします。
+
前のキーが新しいセキュリティキーで上書きされ、無効になります。

+
[NOTE]
====
ダウンロードファイルのパスは、ブラウザのデフォルトのダウンロード先によって異なる場合があります。

====
. キー識別子、パスフレーズ、ダウンロードしたキーファイルの場所を記録し、*閉じる*をクリックします。


.完了後
セキュリティキーを検証して、キーファイルが破損していないことを確認します。
