---
permalink: sm-settings/configure-snmp-alerts.html 
sidebar: sidebar 
keywords: configuration, snmp alerts, identification, one server, storage array, snmp traps, community name, ip address 
summary: 簡易ネットワーク管理プロトコル（SNMP）アラートを設定するには、ストレージアレイのイベントモニタからSNMPトラップを送信できるサーバを少なくとも1つ指定する必要があります。この設定には、サーバのコミュニティ名とIPアドレスが必要です。 
---
= SNMPアラートのコミュニティとデスティネーションを設定する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
簡易ネットワーク管理プロトコル（SNMP）アラートを設定するには、ストレージアレイのイベントモニタからSNMPトラップを送信できるサーバを少なくとも1つ指定する必要があります。この設定には、サーバのコミュニティ名とIPアドレスが必要です。

.作業を開始する前に
* ネットワークサーバにSNMPサービスアプリケーションが設定されている必要があります。イベントモニタからトラップメッセージを送信するためには、このサーバのネットワークアドレス（IPv4アドレスまたはIPv6アドレス）が必要です。複数のサーバを使用できます（最大10台のサーバを使用できます）。
* 印刷可能なASCII文字だけを使用したコミュニティ名が作成されている必要があります。コミュニティ名は、ネットワークサーバのパスワードのような役割を果たす文字列で、通常はネットワーク管理者が作成します。コミュニティを最大256個作成できます。
* SNMPサービスアプリケーションがインストールされたサーバに管理情報ベース（MIB）ファイルをコピーしてコンパイルしておきます。このMIBファイルは、監視および管理されるデータを定義します。
+
MIBファイルがない場合は、ネットアップサポートサイトから入手できます。

+
** に進みます https://mysupport.netapp.com/site/["ネットアップサポート"^]。
** 「*ダウンロード」をクリックします。
** [*ソフトウェア]をクリックします。
** 管理ソフトウェア（SANtricity System Managerなど）を探し、右側の「* Go！*」をクリックします。
** 最新バージョンの[** View & Download**（表示とダウンロード）]をクリックします。
** ページの下部にある[* Continue *（続行）]をクリックします。
** EULA に同意します。
** 下にスクロールしてSNMPトラップのMIBファイル*を探し、リンクをクリックしてファイルをダウンロードします。




.このタスクについて
このタスクでは、トラップの送信先となるSNMPサーバを指定し、設定をテストする方法について説明します。

.手順
. 「*」メニューを選択します。「Settings [Alerts]」を選択します。
. [*SNMP*]タブを選択します。
+
コミュニティがまだ設定されていない場合は、SNMPタブに「コミュニティの設定」と表示されます。

. [コミュニティの設定]を選択します。
+
コミュニティの設定*（Configure Communities *）ダイアログボックスが開きます。

. [*コミュニティ名*]フィールドに、ネットワークサーバーのコミュニティストリングを1つ以上入力し、[保存*]をクリックします。
+
アラートページに「トラップ送信先の追加」と表示されます。

. 「トラップ送信先の追加」を選択します。
+
[トラップ送信先の追加*]ダイアログボックスが開きます。

. 1つ以上のトラップ送信先を入力し、関連するコミュニティ名を選択して、* Add *をクリックします。
+
** *Trap Destination*-- SNMPサービスを実行しているサーバーのIPv4またはIPv6アドレスを入力します
** *コミュニティ名*--ドロップダウンから、このトラップの送信先のコミュニティ名を選択します。（コミュニティ名を1つだけ定義した場合は、その名前がこのフィールドにすでに表示されます）。
** *認証失敗トラップを送信*--コミュニティ名が認識されないためにSNMP要求が拒否された場合にトラップの送信先にアラートを送信するには、このオプション（チェックボックス）を選択します。[*追加]をクリックすると、トラップの送信先と関連するコミュニティ名が[*アラート*]ページの[* SNMP]タブに表示されます。


. トラップが有効であることを確認するには、テーブルからトラップの送信先を選択し、*トラップの送信先のテスト*をクリックして、設定したアドレスにテストトラップを送信します。


.結果
アラート対象のイベントが発生するたびに、イベントモニタからサーバにSNMPトラップが送信されます。
