---
permalink: sm-settings/configure-snmp-mib-variables.html 
sidebar: sidebar 
keywords: snmp alerts, optional, mib, variables, snmp traps, storage array, contact person 
summary: SNMPアラートの場合、必要に応じて、SNMPトラップに表示される管理情報ベース（MIB）変数を設定できます。これらの変数で、ストレージアレイの名前、場所、および担当者を返すことができます。 
---
= SNMP MIB変数を設定します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMPアラートの場合、必要に応じて、SNMPトラップに表示される管理情報ベース（MIB）変数を設定できます。これらの変数で、ストレージアレイの名前、場所、および担当者を返すことができます。

.作業を開始する前に
SNMPサービスアプリケーションがインストールされたサーバにMIBファイルをコピーしてコンパイルしておく必要があります。

MIBファイルがない場合は、次の方法で入手できます。

* に進みます https://mysupport.netapp.com/site/["ネットアップサポート"^]。
* 「*ダウンロード」をクリックします。
* [*ソフトウェア]をクリックします。
* 管理ソフトウェア（SANtricity System Managerなど）を探し、右側の「* Go！*」をクリックします。
* 最新バージョンで* View & Download *をクリックします。
* ページの下部にある[* Continue *（続行）]をクリックします。
* EULA に同意します。
* 下にスクロールしてSNMPトラップのMIBファイル*を探し、リンクをクリックしてファイルをダウンロードします。


.このタスクについて
このタスクでは、SNMPトラップのMIB変数を定義する方法について説明します。これらの変数は、SNMP GetRequestsに対する応答で次の値を返すことができます。

* `_sysName_`(ストレージアレイの名前)
* `_sysLocation_`(ストレージアレイの場所)
* `_sysContact_`(管理者の名前)


.手順
. 「*」メニューを選択します。「Settings [Alerts]」を選択します。
. [*SNMP*]タブを選択します。
. [Configure SNMP MIB Variables]を選択します。
+
SNMP MIB変数の設定ダイアログボックスが開きます。

. 次の値を1つ以上入力し、*保存*をクリックします。
+
** *Name*-- MIB変数`_sysName_`の値。たとえば、ストレージアレイの名前を入力します。
** *場所*-- MIB変数`_sysLocation_`の値。たとえば、ストレージアレイの場所を入力します。
** *Contact *-- MIB変数の値'_sysContact_'。たとえば、ストレージアレイを担当する管理者を入力します。




.結果
これらの値はストレージアレイのアラートのSNMPトラップメッセージに表示されます。
