---
permalink: sm-settings/nvme-terminology.html 
sidebar: sidebar 
keywords: nvme, terms, storage array 
summary: ストレージアレイに関連するNVMeの用語を次に示します。 
---
= NVMeの用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するNVMeの用語を次に示します。

[cols="1a,3a"]
|===
| 期間 | 説明 


 a| 
InfiniBandの略
 a| 
InfiniBand （ IB ）は、ハイパフォーマンスのサーバとストレージシステムの間のデータ転送用の通信標準です。



 a| 
ネームスペース
 a| 
ネームスペースは、ブロックアクセス用にフォーマットされたNVMストレージです。SCSIの論理ユニットに相当し、ストレージアレイではボリュームに関連します。



 a| 
ネームスペースID
 a| 
ネームスペースIDは、NVMeコントローラのネームスペースの一意の識別子です。1~255の値を設定できます。SCSIの論理ユニット番号（LUN）に相当します。



 a| 
NQN
 a| 
NVMe Qualified Name（NQN）は、リモートストレージターゲット（ストレージアレイ）を識別するために使用します。



 a| 
NVM
 a| 
非揮発性メモリ（NVM）は、多くのタイプのストレージデバイスで使用されている永続的メモリです。



 a| 
NVMe
 a| 
Non-Volatile Memory Express（NVMe）は、SSDドライブなどのフラッシュベースのストレージデバイス向けに設計されたインターフェイスです。以前の論理デバイスインターフェイスに比べ、I/Oオーバーヘッドが少なく、パフォーマンスも向上しています。



 a| 
NVMe-oF
 a| 
Non-Volatile Memory Express over Fabrics（NVMe-oF）は、NVMeコマンドとデータをホストとストレージ間でネットワーク経由で転送するための仕様です。



 a| 
NVMeコントローラ
 a| 
NVMeコントローラはホストの接続プロセス中に作成されます。ホストとストレージアレイ内のネームスペースの間のアクセスパスを提供します。



 a| 
NVMeキューです
 a| 
NVMeインターフェイス経由でのコマンドやメッセージの受け渡しに使用されるキューです。



 a| 
NVMe サブシステム
 a| 
NVMeホストに接続されているストレージアレイです。



 a| 
RDMA
 a| 
Remote Direct Memory Access（RDMA）を使用すると、ネットワークインターフェイスカード（NIC）ハードウェアに転送プロトコルを実装することで、サーバとの間でより直接的なデータ移動を実現できます。



 a| 
RoCE
 a| 
RDMA over Converged Ethernet （ RoCE ）は、イーサネットネットワークを介したリモートダイレクトメモリアクセス（ RDMA ）を可能にするネットワークプロトコルです。



 a| 
SSD の場合
 a| 
ソリッドステートディスク（ SSD ）は、ソリッドステートメモリ（フラッシュ）を使用してデータを永続的に格納するデータストレージデバイスです。SSD は従来のハードドライブをエミュレートしたものであり、ハードドライブと同じインターフェイスで利用できます。

|===