---
permalink: sm-settings/unlock-drives-using-an-internal-security-key.html 
sidebar: sidebar 
keywords: secure, enable, storage array, appropriate, importing, new storage, drive 
summary: セキュリティ有効ドライブをストレージアレイ間で移動する場合は、適切なセキュリティキーを新しいストレージアレイにインポートする必要があります。キーをインポートすると、ドライブ上のデータのロックが解除されます。 
---
= セキュリティキーを使用してドライブのロックを解除します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セキュリティ有効ドライブをストレージアレイ間で移動する場合は、適切なセキュリティキーを新しいストレージアレイにインポートする必要があります。キーをインポートすると、ドライブ上のデータのロックが解除されます。

.作業を開始する前に
* （ドライブの移動先となる）ターゲットストレージアレイでセキュリティキーが設定済みである必要があります。移行されたドライブのキーはターゲットストレージアレイのキーに変更されます。
* ロックを解除するドライブに関連付けられているセキュリティキーを把握しておく必要があります。
* セキュリティキーファイルは管理クライアント（System Managerへのアクセスに使用するブラウザを備えたシステム）にあります。別のシステムで管理されるストレージアレイにドライブを移動する場合は、その管理クライアントにセキュリティキーファイルを移動する必要があります。


このタスクでは、あるストレージアレイから取り外されて別のストレージアレイに再度取り付けられたセキュリティ有効ドライブ内のデータのロックを解除する方法について説明します。アレイでドライブが検出されると、再配置されたこれらのドライブに対して「Needs Attention」状態と「Security Key Needed」ステータスが表示されます。ドライブのセキュリティキーをストレージアレイにインポートすることで、ドライブデータのロックを解除できます。このプロセスでは、セキュリティキーファイルを選択して、キーのパスフレーズを入力します。

[NOTE]
====
パスフレーズはストレージアレイの管理者パスワードとは異なります。

====
新しいストレージアレイに取り付けられている他のセキュリティ有効ドライブでは、インポートするセキュリティキーとは別のセキュリティキーが使用される場合があります。インポートプロセスでは、取り付けるドライブのデータのロック解除にのみ古いセキュリティキーが使用されます。ロック解除プロセスが成功すると、新しく取り付けたドライブのキーがターゲットストレージアレイのセキュリティキーに変更されます。

.手順
. メニューを選択します。[設定][システム]。
. セキュリティキー管理*で、*セキュアドライブのロック解除*を選択します。
+
[セキュアドライブのロック解除]ダイアログボックスが開きます。セキュリティキーを必要とするドライブがテーブルに表示されます。

. *オプション：ドライブ番号にカーソルを合わせると、ドライブの場所（シェルフ番号とベイ番号）が表示されます。
. [*参照]をクリックし、ロックを解除するドライブに対応するセキュリティキーファイルを選択します。
+
選択したキーファイルがダイアログボックスに表示されます。

. このキーファイルに関連付けられているパスフレーズを入力します。
+
入力した文字はマスクされます。

. [ロック解除]をクリックします。
+
ロック解除処理が成功すると、「The associated secure drives have been unlocked」というメッセージを示すダイアログボックスが表示されます。



すべてのドライブがロックされたあとでロック解除されると、ストレージアレイ内の各コントローラがリブートされます。ただし、ターゲットストレージアレイ内の一部のドライブがすでにロック解除されている場合、コントローラはリブートされません。
