---
permalink: sm-settings/use-ca-signed-certificates-for-controllers.html 
sidebar: sidebar 
keywords: ca signed certificate, secure communication, controller, browser, system manager 
summary: コントローラとSystem Managerへのアクセスに使用されるブラウザとの間のセキュアな通信を確立するために、CA署名証明書を取得できます。 
---
= コントローラのCA署名証明書を使用する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラとSystem Managerへのアクセスに使用されるブラウザとの間のセキュアな通信を確立するために、CA署名証明書を取得できます。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、証明書の機能は表示されません。


CA署名証明書の使用は、3つの手順で構成される手順 です。



== 手順1：コントローラのCSRを作成および送信します

最初にストレージアレイの各コントローラの証明書署名要求（CSR）ファイルを生成し、そのファイルを認証局（CA）に送信する必要があります。

.作業を開始する前に
* 各コントローラのIPアドレスまたはDNS名を確認しておく必要があります。


CSRは、組織に関する情報、コントローラのIPアドレスまたはDNS名、およびコントローラのWebサーバを識別するキーペアを提供します。このタスクでは、ストレージアレイにコントローラが1つしかない場合はCSRファイルが1つ、コントローラが2つある場合は2つ生成されます。

[CAUTION]
====
CAに送信したあとで新しいCSRを生成しないでください。CSRの生成時に、システムでは秘密鍵と公開鍵のペアが作成されます。公開鍵はCSRの一部であり、秘密鍵はキーストアに保持されます。署名済み証明書を受け取ってキーストアにインポートすると、システムでは秘密鍵と公開鍵の両方が元のペアになります。そのため、CSRをCAに送信したあとで新しいCSRを生成しないでください。新しいキーを生成すると、コントローラではCAから受け取った証明書が機能しなくなります。

====
.手順
. [*]メニューを選択します。[設定][証明書]*。
. [*アレイ管理*]タブで、[* CSR全体*]を選択します。
+
[NOTE]
====
2台目のコントローラの自己署名証明書を受け入れるよう求めるダイアログボックスが表示された場合は、*自己署名証明書を受け入れる*をクリックして続行します。

====
. 次の情報を入力し、[次へ*]をクリックします。
+
** *組織*--会社または組織の正式名称。Inc.やCorp.などの接尾辞も含めて入力してください
** *組織単位（オプション）*--証明書を処理している組織の部門。
** *市区町村*--ストレージアレイまたは事業の所在地である市区町村。
** *都道府県（オプション）*-ストレージアレイまたは事業の所在地である都道府県。
** *国のISOコード*--自国を表す2桁のISO（国際標準化機構）コード（USなど）。


+
[CAUTION]
====
一部のフィールドには、コントローラのIPアドレスなどの適切な情報があらかじめ入力されています。事前入力された値は、明らかな間違いでないかぎり変更しないでください。たとえば、CSRをまだ作成していない場合、コントローラのIPアドレスは「localhost」に設定されます。 この場合は、「localhost」をコントローラのDNS名またはIPアドレスに変更する必要があります。

====
. ストレージアレイ内のコントローラAに関する次の情報を確認または入力します。
+
** *コントローラAの共通名*--コントローラAのIPアドレスまたはDNS名がデフォルトで表示されますこのアドレスが正しいことを確認してください。ブラウザでSystem Managerにアクセスする際に入力したアドレスと正確に一致している必要があります。
** *コントローラAの代替IPアドレス*-共通名がIPアドレスの場合は、コントローラAの追加のIPアドレスまたはエイリアスをオプションで入力できます複数指定する場合は、カンマで区切って入力します。
** *コントローラAの代替DNS名*--共通名がDNS名の場合は、コントローラAの追加のDNS名を入力します複数指定する場合は、カンマで区切って入力します。代替DNS名がない場合は、最初のフィールドに入力したDNS名をここにコピーします。ストレージアレイにコントローラが1台しかない場合は、「完了」ボタンを使用できます。ストレージアレイにコントローラが2台ある場合は、* Next *ボタンを使用できます。


+
[NOTE]
====
CSR要求を最初に作成するときは、[この手順をスキップ]リンクをクリックしないでください。このリンクは、エラーからリカバリする場合に使用します。CSR要求が一方のコントローラで失敗し、もう一方のコントローラで失敗することがあります。このリンクを使用すると、コントローラAでCSRがすでに定義されている場合はその作成をスキップし、コントローラBでCSRを再作成する次の手順に進むことができます

====
. コントローラが1台しかない場合は、[完了]をクリックします。コントローラが2台ある場合は、[次へ]をクリックしてコントローラBの情報を入力し（上記と同じ）、[完了]をクリックします。
+
シングルコントローラの場合は、1つのCSRファイルがローカルシステムにダウンロードされます。デュアルコントローラの場合は、2つのCSRファイルがダウンロードされます。ダウンロードフォルダの場所は、ブラウザによって異なります。

. ダウンロードしたCSRファイルの場所を確認します。フォルダの場所はブラウザによって異なります。
. CSRファイルをCAに送信し、PEM形式の署名済み証明書を要求します。
. CAから証明書が返されるまで待ってから、に進みます  2: Import signed certificates for controllers。




== 手順2：コントローラの署名済み証明書をインポートする

署名済み証明書を受け取ったあと、コントローラのファイルをインポートします。

.作業を開始する前に
* 署名済み証明書ファイルをCAから受け取っておきます。
* ファイルがローカルシステム上にある必要があります。
* CAからチェーン証明書（たとえば、.p7bファイル）が提供された場合は、チェーンファイルを個々のファイル（ルート証明書、1つ以上の中間証明書、コントローラを識別するサーバ証明書）に展開する必要があります。Windowsのcertmgrユーティリティーを使用してファイルを展開できます(右クリックして[*menu: All Tasks[Export]*)を選択します)エクスポートが完了すると、チェーン内の証明書ファイルごとに1つのCERファイルが表示されます。


このタスクでは、証明書ファイルをアップロードする方法について説明します。

.手順
. [*]メニューを選択します。[設定][証明書]*。
. [* Array Management*（アレイ管理*）]タブで、[* Import*（インポート*）]を選択し
+
証明書ファイルをインポートするためのダイアログボックスが表示されます。

. 「*参照」ボタンをクリックして、最初にルートファイルと中間ファイルを選択してから、コントローラの各サーバ証明書を選択します。ルートファイルと中間ファイルは両方のコントローラで同じです。サーバ証明書のみコントローラごとに一意です。
+
ファイル名がダイアログボックスに表示されます。

. [* インポート * ] をクリックします。
+
ファイルがアップロードされて検証されます。



セッションは自動的に終了します。証明書を有効にするには、再度ログインする必要があります。再度ログインすると、新しいCA署名証明書がセッションに使用されます。
