---
permalink: sm-support/drive-firmware-upgrades.html 
sidebar: sidebar 
keywords: drive, firmware, control, low, level, operating, characteristics, periodically, manufacturer, release, update, add, new, features, improve, performance, fix, detects 
summary: ドライブファームウェアは、ドライブの細かな動作特性を制御します。新機能の追加、パフォーマンスの向上、および不具合の修正のために、ドライブメーカーはドライブファームウェアの更新を定期的にリリースしています。 
---
= ドライブファームウェアのアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブファームウェアは、ドライブの細かな動作特性を制御します。新機能の追加、パフォーマンスの向上、および不具合の修正のために、ドライブメーカーはドライブファームウェアの更新を定期的にリリースしています。



== ドライブファームウェアのオンラインアップグレードとオフラインアップグレード

ドライブファームウェアのアップグレード方式には、オンラインとオフラインの 2 種類があります。



== オンライン

オンラインアップグレードでは、ドライブが一度に 1 つずつ順番にアップグレードされます。ストレージアレイでの I/O の処理はアップグレードの実行中も継続されます。I/O を停止する必要はありませんオンラインアップグレードが可能なドライブの場合は、自動的にオンライン方式が使用されます。

オンラインアップグレードを実行できるドライブには、次のものがあります。

* 「最適」状態のプール内のドライブ
* 「最適」状態の冗長化されたボリュームグループ内のドライブ（ RAID 1 、 RAID 5 、および RAID 6 ）
* 未割り当てのドライブ
* スタンバイのホットスペアドライブ


ドライブファームウェアのオンラインアップグレードには数時間かかることがあり、その間はストレージアレイでボリューム障害が発生する可能性があります。ボリューム障害は次の状況で発生する可能性があります。

* RAID 1 または RAID 5 のボリュームグループで、あるドライブをアップグレードしているときに 1 本のドライブで障害が発生した場合。
* RAID 6 のプールまたはボリュームグループで、あるドライブをアップグレードしているときに別の 2 本のドライブで障害が発生した場合。




== オフライン（並行処理）

オフラインアップグレードでは、同じドライブタイプのすべてのドライブが同時にアップグレードされます。この方式では、選択したドライブに関連付けられているボリュームへの I/O アクティビティを停止する必要があります。複数のドライブを同時に並行してアップグレードできるため、全体的なダウンタイムは大幅に短縮されます。オフラインアップグレードしか実行できないドライブの場合は、自動的にオフライン方式が使用されます。

次のドライブではオフライン方式を使用する必要があります。

* 非冗長ボリュームグループ内のドライブ（ RAID 0 ）
* 最適状態でないプールまたはボリュームグループ内のドライブ
* SSD キャッシュ内のドライブ




== 互換性

各ドライブファームウェアファイルには、ファームウェアが実行されるドライブタイプに関する情報が含まれています。ファームウェアファイルは互換性のあるドライブにのみダウンロードできます。アップグレードプロセスの実行中に、 System Manager で自動的に互換性がチェックされます。
