---
permalink: um-certificates/use-ca-signed-certificate-um.html 
sidebar: sidebar 
keywords: ca certificate, secure, access, management, system, unified manager 
summary: Unified Managerをホストする管理システムへのセキュアなアクセスを確立するために、CA署名証明書を取得してインポートできます。 
---
= CA署名証明書を使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerをホストする管理システムへのセキュアなアクセスを確立するために、CA署名証明書を取得してインポートできます。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、証明書の機能は表示されません。


.このタスクについて
CA署名証明書の使用は、2つの手順で構成された手順 です。



== 手順1：CSRを作成および送信します

最初に証明書署名要求（CSR）ファイルを生成し、そのファイルをCAに送信する必要があります。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、証明書の機能は表示されません。


.このタスクについて
このタスクでは、Unified ManagerとWeb Services Proxyをホストするシステムの署名付き管理証明書を受け取るためにCAに送信するCSRファイルを生成する方法について説明します。組織に関する情報とともに、ホストシステムのIPアドレスまたはDNS名を指定する必要があります。

[CAUTION]
====
CAに送信したあとで新しいCSRを生成しないでください。CSRの生成時に、システムでは秘密鍵と公開鍵のペアが作成されます。公開鍵はCSRの一部であり、秘密鍵はキーストアに保持されます。署名済み証明書を受け取ってキーストアにインポートすると、システムでは秘密鍵と公開鍵の両方が元のペアになります。そのため、CSRをCAに送信したあとで新しいCSRを生成しないでください。新しいキーを生成すると、コントローラではCAから受け取った証明書が機能しなくなります。

====
.手順
. [証明書管理]を選択します。
. [*管理（Management）]タブで、[* CSR全体*（* Complete CSR *）]を選択します。
. 次の情報を入力し、[次へ*]をクリックします。
+
** *組織*--会社または組織の正式名称。Inc.やCorp.などの接尾辞も含めて入力してください
** *組織単位（オプション）*--証明書を処理している組織の部門。
** *市区町村*--ホストシステムまたは事業の所在地である市区町村。
** *都道府県(オプション)*--ホストシステムまたは事業の所在地である都道府県。
** *国のISOコード*--自国を表す2桁のISO（国際標準化機構）コード（USなど）。


. ホストシステムに関する次の情報を入力します。
+
** *共通名*-- WebサービスプロキシがインストールされているホストシステムのIPアドレスまたはDNS名。このアドレスが正しいことを確認してください。ブラウザでUnified Managerにアクセスする際に入力したアドレスと正確に一致している必要があります。http：//またはhttps：//を含めないでください。
** *代替IPアドレス*--共通名がIPアドレスの場合は'オプションでホストシステムの追加のIPアドレスまたはエイリアスを入力できます複数指定する場合は、カンマで区切って入力します。
** *代替DNS名*--共通名がDNS名の場合は'ホストシステムの追加のDNS名を入力します複数指定する場合は、カンマで区切って入力します。代替DNS名がない場合は、最初のフィールドに入力したDNS名をここにコピーします。


. [ 完了 ] をクリックします。
+
CSRファイルがローカルシステムにダウンロードされます。ダウンロードフォルダの場所は、ブラウザによって異なります。

. CSRファイルをCAに送信し、PEM形式またはDER形式の署名済み証明書を要求します。


.完了後
CAから証明書ファイルが返されるまで待ってから、に進みます link:step-3-import-management-certificates-unified.html["手順2：管理証明書をインポートする"]。



== 手順2：管理証明書をインポートする

署名済み証明書を受け取ったあと、Unified Managerインターフェイスがインストールされているホストシステムの証明書チェーンをインポートします。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、証明書の機能は表示されません。
* 証明書署名要求（.CSRファイル）を生成してCAに送信しておきます。
* 信頼された証明書ファイルをCAから受け取っておきます。
* 証明書ファイルがローカルシステムにインストールされている必要があります。
* CAからチェーン証明書（たとえば、.p7bファイル）が提供された場合は、チェーンファイルを個々のファイル（ルート証明書、1つ以上の中間証明書、サーバ証明書）に展開する必要があります。Windowsのcertmgrユーティリティーを使用してファイルを展開できます(右クリックして[*menu: All Tasks[Export]*)を選択します)エクスポートが完了すると、チェーン内の証明書ファイルごとに1つのCERファイルが表示されます。


.手順
. [証明書管理]を選択します。
. [*管理（* Management）]タブで、[*インポート（* Import）]を選択します。
+
証明書ファイルをインポートするためのダイアログボックスが表示されます。

. [*Browse*](参照)をクリックして、最初にルートファイルと中間ファイルを選択し、次にサーバー証明書を選択します。
+
ファイル名がダイアログボックスに表示されます。

. [* インポート * ] をクリックします。


.結果
ファイルがアップロードされて検証されます。証明書の情報は、証明書の管理ページに表示されます。
