---
permalink: um-admin/home-page-unified.html 
sidebar: sidebar 
keywords: unified, manager, web, interface, allow, manage, multiple, storage, arrays, single, view 
summary: Unified ManagerはWebベースのインターフェイスであり、1つのビューで複数のストレージアレイを管理することができます。 
---
= インターフェイスの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified ManagerはWebベースのインターフェイスであり、1つのビューで複数のストレージアレイを管理することができます。



== メインページ

Unified Managerにログインすると、メインページが開き、* Manage-All *が表示されます。このページから、ネットワーク内で検出されたストレージアレイのリストをスクロールして、そのステータスを表示し、1つのアレイまたはアレイグループに対して処理を実行できます。



== ナビゲーションサイドバー

ナビゲーションサイドバーには次の情報が表示されます。

* *管理*--ネットワーク内のストレージアレイの検出、アレイのSANtricity System Managerの起動、1つのアレイから複数のアレイへの設定のインポート、アレイグループの管理を行います。設定のインポートやアレイグループの作成など、アレイに対する処理を実行するには、アレイ名の横にあるチェックボックスを選択します。各行の最後にある省略記号には'名前の変更など'1つのアレイでの操作を実行するためのインラインメニューがあります
* *オペレーション*--あるアレイから別のアレイへの設定のインポートなど'バッチ操作の進行状況を表示します
+
[NOTE]
====
ストレージアレイのステータスが最適でない場合は、一部の処理は使用できません。

====
* *証明書管理*--ブラウザとクライアント間の認証に使用する証明書を管理します
* *アクセス管理*-- Unified Managerインターフェイスのユーザ認証を確立します。
* *サポート*--テクニカルサポートのオプション、リソース、連絡先を表示します。




== バナー機能

上部のバナーから、Unified Managerインターフェイスのヘルプやその他のドキュメントにアクセスできます。ログイン名の横にあるドロップダウンから管理オプションにアクセスすることもできます。
